version: '3.2'
services:
  php:
    build:
        context: ./php
        dockerfile: Dockerfile
    container_name: php
    volumes:
        - './api:/var/www/html'
    depends_on:
        - mariadb

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
     - "80:80"
    volumes:
     - "./nginx/:/etc/nginx/conf.d"
     - "./api/:/var/www/html"
    external_links:
     - mariadb:mariadb
     - phpmyadmin:phpmyadmin
    links:
     - 'php'

  mariadb:
    image: mariadb:10.3.9
    container_name: mariadb
    restart: 'on-failure'
    environment:
      MYSQL_ROOT_PASSWORD: secretFEF2f32fwec23h64
    volumes:
     - "./mariadb/:/var/lib/mysql"
     
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpMyAdmin
    restart: 'on-failure'
    environment:
     - "PMA_HOST=mariadb"
     - "PMA_PORT=3306"
    external_links:
     - mariadb:mariadb
    volumes:
     - "./phpmyadmin/sessions:/sessions"