version: '3.2'
services:
  nginx:
    image: richarvey/nginx-php-fpm:latest
    container_name: nginx
    restart: always
    ports:
     - "8089:80"
    volumes:
     - "./nginx/:/etc/nginx"
     - "./api/:/var/www/html"
    external_links:
     - mariadb:mariadb
     - phpmyadmin:phpmyadmin
  mariadb:
    image: mariadb
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secretFEF2f32fwec23h64
    volumes:
     - "./mariadb/:/var/lib/mysql"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpMyAdmin
    restart: always
    environment:
     - "PMA_HOST=mariadb"
     - "PMA_PORT=3306"
    external_links:
     - mariadb:mariadb
    volumes:
     - "./phpmyadmin/sessions:/sessions"